// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnologicalProductionWebApi.DB;

#nullable disable

namespace TechnologicalProductionWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnologicalProductionWebApi.Models.Contract", b =>
                {
                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId", "BuildingId");

                    b.HasIndex("BuildingId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            TypeId = 5,
                            BuildingId = 1,
                            Count = 1,
                            Name = "Contract15"
                        },
                        new
                        {
                            TypeId = 5,
                            BuildingId = 6,
                            Count = 3,
                            Name = "Contract65"
                        });
                });

            modelBuilder.Entity("TechnologicalProductionWebApi.Models.ProductionBuilding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("FreeSquare")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Square")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ProductionBuildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FreeSquare = 100.0,
                            Name = "Building 1",
                            Square = 100.0
                        },
                        new
                        {
                            Id = 2,
                            FreeSquare = 125.0,
                            Name = "Building 2",
                            Square = 125.0
                        },
                        new
                        {
                            Id = 3,
                            FreeSquare = 88.0,
                            Name = "Building 3",
                            Square = 88.0
                        },
                        new
                        {
                            Id = 4,
                            FreeSquare = 200.0,
                            Name = "Building 4",
                            Square = 200.0
                        },
                        new
                        {
                            Id = 5,
                            FreeSquare = 165.0,
                            Name = "Building 5",
                            Square = 165.0
                        },
                        new
                        {
                            Id = 6,
                            FreeSquare = 346.0,
                            Name = "Building 6",
                            Square = 346.0
                        });
                });

            modelBuilder.Entity("TechnologicalProductionWebApi.Models.TypeOfEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Square")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TypeOfEquipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Type 1",
                            Square = 10.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Type 2",
                            Square = 25.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Type 3",
                            Square = 18.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Type 4",
                            Square = 37.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Type 5",
                            Square = 60.0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Type 6",
                            Square = 5.0
                        });
                });

            modelBuilder.Entity("TechnologicalProductionWebApi.Models.Contract", b =>
                {
                    b.HasOne("TechnologicalProductionWebApi.Models.ProductionBuilding", "ProductionBuilding")
                        .WithMany("Contracts")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnologicalProductionWebApi.Models.TypeOfEquipment", "TypeOfEquipment")
                        .WithMany("Contracts")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionBuilding");

                    b.Navigation("TypeOfEquipment");
                });

            modelBuilder.Entity("TechnologicalProductionWebApi.Models.ProductionBuilding", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("TechnologicalProductionWebApi.Models.TypeOfEquipment", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
